blank_issues_enabled: false  # "ë¹ˆ ì´ìŠˆ ë§Œë“¤ê¸°" ë²„íŠ¼ ë¹„í™œì„±í™”

contact_links:
  - name: ğŸ”— CMS ê´€ë ¨ ë¦¬í¬
    url: https://github.com/orgs/handong-app/repositories?q=cms
    about: "CMS í”„ë¡œì íŠ¸ ê´€ë ¨ ë¦¬í¬ì§€í† ë¦¬ ëª©ë¡ ì…ë‹ˆë‹¤."
  - name: ğŸ“‘ CMS Project
    url: https://github.com/orgs/handong-app/projects/5/views/3
    about: "CMS í”„ë¡œì íŠ¸ë¥¼ ê´€ë¦¬í•˜ëŠ” í”„ë¡œì íŠ¸ ë³´ë“œì…ë‹ˆë‹¤."
